# https: // leetcode.com/problems/find-the-difference/submissions/916889897/

# Runtime: 23 ms, faster than 99.99% of Python3 online submissions for Find the Difference.
# Memory Usage: 13.8 MB, less than 92.45% of Python3 online submissions for Find the Difference.
#
# Problem:
# You are given two strings s and t. String t is generated by random shuffling 
# string s and then add one more letter at a random position.

# Return the letter that was added to t.


# hello companies, yes I know about string interpretation, but
# this is probably the least interesting file for you to look at.
# Maybe try 0704 or 0589?
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for char in s:
            t = t.replace(char, "", 1)
        return t
